credentials:
  usernames:
    admin: # can see all projects
      email: admin@gmail.com
      name: LLM Admin
      password: admin
cookie:
  expiry_days: 30
  key: random_signature_key_llm # Must be string
  name: random_cookie_name
