FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# COPY . .

EXPOSE 80

CMD ["streamlit", "run", "web.py", "--server.port", "80", "--server.address", "0.0.0.0"]
