version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    working_dir: /app
    environment:
      TZ: "Asia/Shanghai"
    command: >
      streamlit run worker_web.py --server.port 9876 --server.address 0.0.0.0 --server.runOnSave true --server.fileWatcherType poll --browser.gatherUsageStats false
    volumes:
      - ./:/app
    ports:
      - "9876:9876"
    depends_on:
      - mysql
    networks:
      - app-network

  request:
    build:
      context: .
      dockerfile: Dockerfile.worker
    command: python observer_request.py
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - mysql
    networks:
      - app-network

  queue:
    build:
      context: .
      dockerfile: Dockerfile.worker
    command: python observer_queue.py
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - mysql
      - redis
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "3679:6379"
    networks:
      - app-network

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: AIoqnh17a1
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
